### ISSUE TITLE
Cannot retrieve Google Calendar refresh token

### ISSUE THREAD

**Issue by letsdothis2023** [MMRIZE/MMM-CalDAV#14]
RaspberryPi 4B
Debian 12, Bookworm
All OS and modules updated

For adding a Google account/calendar, I followed the instructions, but at step 7. after executing command:

```
 $ cd ~/MagicMirror/modules/MMM-CalDAV
node google_auth.js GOOGLE_
Server listening on http://localhost:3000, When the browser is not opened, open it manually
(node:1005261) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

No refreshToken issued. 
Retried with deprecation trace for verbose error:

```
$~/MagicMirror/modules/MMM-CalDAV $ node --trace-deprecation google_auth.js GOOGLE_
Server listening on http://localhost:3000, When the browser is not opened, open it manually
(node:1005433) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
    at node:punycode:3:9
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/realm:399:7)
    at BuiltinModule.compileForPublicLoader (node:internal/bootstrap/realm:338:10)
    at loadBuiltinModule (node:internal/modules/helpers:110:7)
    at Function._load (node:internal/modules/cjs/loader:1093:17)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Module.require (node:internal/modules/cjs/loader:1329:12)
    at require (node:internal/modules/helpers:136:16)
    at Object.<anonymous> (/home/MagicMirrorPi/MagicMirror/modules/MMM-CalDAV/node_modules/whatwg-url/lib/url-state-machine.js:2:18)
```

I followed the remaining instructions, in case the login would happen at first fetch, but no luck. Here are the errors I received after restarting MagicMirror:

```
 [ERROR] Error: Oauth credentials missing: authorizationCode,redirectUrl
    at /home/MagicMirrorPi/MagicMirror/modules/MMM-CalDAV/node_modules/tsdav/dist/tsdav.cjs.js:1292:15
    at Generator.next (<anonymous>)
    at /home/MagicMirrorPi/MagicMirror/modules/MMM-CalDAV/node_modules/tsdav/dist/tsdav.cjs.js:45:71
    at new Promise (<anonymous>)
    at __awaiter (/home/MagicMirrorPi/MagicMirror/modules/MMM-CalDAV/node_modules/tsdav/dist/tsdav.cjs.js:41:12)
    at fetchOauthTokens (/home/MagicMirrorPi/MagicMirror/modules/MMM-CalDAV/node_modules/tsdav/dist/tsdav.cjs.js:1283:43)
    at /home/MagicMirrorPi/MagicMirror/modules/MMM-CalDAV/node_modules/tsdav/dist/tsdav.cjs.js:1354:24
    at Generator.next (<anonymous>)
    at /home/MagicMirrorPi/MagicMirror/modules/MMM-CalDAV/node_modules/tsdav/dist/tsdav.cjs.js:45:71
    at new Promise (<anonymous>)
    at __awaiter (/home/MagicMirrorPi/MagicMirror/modules/MMM-CalDAV/node_modules/tsdav/dist/tsdav.cjs.js:41:12)
    at getOauthHeaders (/home/MagicMirrorPi/MagicMirror/modules/MMM-CalDAV/node_modules/tsdav/dist/tsdav.cjs.js:1348:42)
    at DAVClient.<anonymous> (/home/MagicMirrorPi/MagicMirror/modules/MMM-CalDAV/node_modules/tsdav/dist/tsdav.cjs.js:1528:47)
    at Generator.next (<anonymous>)
    at /home/MagicMirrorPi/MagicMirror/modules/MMM-CalDAV/node_modules/tsdav/dist/tsdav.cjs.js:45:71
    at new Promise (<anonymous>)
```

and: 

```
[ERROR] Calendar Error. Could not fetch calendar:  https://calendar.google.com/calendar/ical/REDACTED/basic.ics TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at listOnTimeout (node:internal/timers:545:9)
    at process.processTimers (node:internal/timers:519:7) {
  [cause]: AggregateError [ETIMEDOUT]:
      at internalConnectMultiple (node:net:1118:18)
      at internalConnectMultiple (node:net:1186:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1712:5)
      at listOnTimeout (node:internal/timers:583:11)
      at process.processTimers (node:internal/timers:519:7) {
    code: 'ETIMEDOUT',
    [errors]: [ [Error], [Error] ]
  }
}
```

I'd gladly take any feedback to get me sorted out. Thank you!

**Comment by letsdothis2023** [comment]
In it helps: on subsequent reboots of MagicMirror, only the first error exists. Perhaps after a longer period of time the second error will return.

I also tested with 2 different OAuth services: one established a few months and a new one just for this project, no resolution. For both, I added my account as a tester/user, and ensured both are "in production".

**Comment by eouia** [comment]
Deprecation warning is not related. You can ignore it.  (Deprecation trace is not needed also.)
When you execute `node google_auth.js`, it should open the browser. Did it? (It is necessary to get permission auth from Google.)
Ref. this; https://github.com/MMRIZE/MMM-CalDAV/wiki/Setup-for-Google-Calendar

**Comment by letsdothis2023** [comment]
I couldn’t get the browser to launch with any method I tried. 

I had followed all the steps twice, an existing Oauth app setup for Home Assistant, and a new one just for this. I retried step 7 multiple times for each attempt. 

The only step I believe is implied, is that I was accessing and processing the steps headless over SSH. On a retry, I connected via SSH and with VNC, but no change. So I opened the browser via VNC, and retried, no change. 
When I get the chance next, I’ll try opening the terminal through VNC and run the code. 
If that’s doesn’t work, I’ll find a monitor and connect it and try that way. 

If you think of anything else, let me know. Thank you!

**Comment by eouia** [comment]
When you execute `google_auth.js`, you can see message something like this;
![image](https://github.com/user-attachments/assets/f24720da-1268-4ae7-b02e-8372d69aede6)
When you open `http://localhost:3000` manually (but in the target device), it will automatically be redirected to the URL that can enter the auth process.
However, you are trying  headless-remote approach. Hmmmm. 
I'll add some code to reveal the target URL that can be opened on another device by hand.

**Comment by eouia** [comment]
I fixed. #15

**Comment by letsdothis2023** [comment]
Success, thank you!

I am currently stuck at some setting in the main MM config file. For config under the calendar module, I mimicked the ICLOUD example, but it doesn't seem to work for Google calendars.

 ```
                                       {
                                                url: "http://localhost:8080/CALDAV/GOOGLE_**MyCalendarName**.ics",
                                                name: "**MyCalendarDisplayName**",
                                                color: "dark-green",
                                                auth: {
                                                        user: "**myusername**",
                                                        pass: "**mypassword**",
                                                        method: "basic",
                                                }
                                        },
```
My CalDAV module config:

```
                                { //
                                        envPrefix: "GOOGLE_",
                                        serverUrl: "https://apidata.googleusercontent.com/caldav/v2/",
                                        authMethod: 'Oauth',
                                        targets: [
                                                { displayName: "**MyCalendarDisplayName**"},
                                        ],
                                        updateInterval: 1000 * 60 * 30,
                                },
```
If you're able to point me in the right direction here, I'd appreciate it.

**Comment by eouia** [comment]
What is the symptom? Log? was there some feed created? (`/storage/.GOOGLE_something.ics`)

**Comment by letsdothis2023** [comment]
No .ics created in ~/MMM-CalDAV/service folder. Only ICLOUD .ics file there.
```
~/MagicMirror/modules/MMM-CalDAV/service $ ls -a
.  ..  .ICLOUD_Family.ics  placeholder.txt
```
Is there somewhere else I can find a trace that the service is running?

Here is the error I receive after running npm start:
```
[ERROR] Calendar Error. Could not fetch calendar:  http://localhost:8080/CALDAV/GOOGLE_**MyCalendarDisplayName**.ics Error: Not Found
    at NodeHelper.checkFetchStatus (/home/MagicMirrorPi/MagicMirror/js/node_helper.js:102:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
Thanks again for any help. 
As a side note, I tried using the secret calendar address from Google, but there appears to be an issue with all-day events. They shift when imported by at least one day forward. I did not detail this info, and I'd need to look into it more to provide details.

**Comment by eouia** [comment]
I’m not sure if this applies to your issue, but I’ll explain a common misunderstanding that first-time users of `MMM-CalDAV` often encounter.

The operation of `MMM-CalDAV` can be a bit tricky. This module connects to a CalDAV server (like Google Calendar), retrieves calendar data, saves it locally on the device (e.g., a Raspberry Pi) in a file format like `.GOOGLE_xxx.ics`, and then makes it readable by the `calendar` module. 

For this reason, during the very first run after installing `MMM-CalDAV`, a timing issue can occur. While `MMM-CalDAV` is still in the process of fetching data from the server, the `calendar` module often tries to read the `.ics` file before the data retrieval is complete. This can lead to the `fetch error` you observed.

This issue usually resolves itself by the second fetching cycle because `MMM-CalDAV` will have already created the `.ics` file during the previous cycle. (For the same reason, if calendar information is updated, those updates will only reflect after one cycle.)

Many users often misunderstand this aspect.

The usual solutions are as follows:  
1. Just leave it alone. After a suitable amount of time (after one cycle), `MMM-CalDAV` should create the `.ics` file, and the `calendar` module will be able to read it.  
2. Alternatively, stop and restart MagicMirror. Since `MMM-CalDAV` would have created the `.ics` file during the previous run, the `calendar` module will be able to use it immediately upon restarting MagicMirror.  

However, if the issue persists for another reason, we’ll need log files. To simplify the process:  
1. Back up your current `config.js` file and create a new one for testing purposes.  
2. In the new `config.js`, remove all other modules except for `MMM-CalDAV` and the `clock` module. (You don’t need the `calendar` module.)  
3. If you’re using `pm2`, stop it.  
4. Open the Terminal, navigate to the MagicMirror directory, and run `npm run start:dev`. This will display backend logs in the terminal and open the front-end dev console, where you can view front-end logs.  
5. Copy or capture any suspicious parts and share them.

**Comment by mmclane** [comment]
I am having an issue too.  This is the error I see at the moment:
```
[2024-12-20 16:27:49.221] [ERROR] FetchError: request to https://apidata.googleusercontent.com/caldav/v2/c_classroomfb96f94c%40group.calendar.google.com/events/ failed, reason: 
    at ClientRequest.<anonymous> (/home/admin/MagicMirror/modules/MMM-CalDAV/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:519:28)
    at emitErrorEvent (node:_http_client:101:11)
    at TLSSocket.socketErrorListener (node:_http_client:504:5)
    at TLSSocket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
```
